import React, { useState } from 'react';
import AppLayout from '../../components/layout/AppLayout';
import { Card, Button, Input } from '../../components/ui';
import { SearchIcon, HelpCircleIcon, FileTextIcon, TargetIcon, RouteIcon, MicIcon, ChevronDownIcon } from '../../components/ui/Icons';
import './Help.css';

const Help = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFaq, setExpandedFaq] = useState(null);

  const popularTopics = [
    { title: 'Resume Analysis', icon: <FileTextIcon size={20} />, link: '/resume-analysis' },
    { title: 'Resume Builder', icon: <FileTextIcon size={20} />, link: '/resume-builder' },
    { title: 'Job Optimization', icon: <TargetIcon size={20} />, link: '/job-optimization' },
    { title: 'Career Roadmap', icon: <RouteIcon size={20} />, link: '/career-roadmap' },
    { title: 'AI Interviewer', icon: <MicIcon size={20} />, link: '/ai-interviewer' },
    { title: 'Account & Settings', icon: <HelpCircleIcon size={20} />, link: '/settings' }
  ];

  const faqs = [
    {
      question: 'What is ATS scoring?',
      answer: 'ATS (Applicant Tracking System) scoring measures how well your resume is optimized for automated screening systems used by employers. A higher ATS score (80%+) means your resume is more likely to pass initial screening.'
    },
    {
      question: 'How do I optimize my resume for a specific job?',
      answer: 'Use the Job Optimization feature to upload a job description. Our AI will analyze the requirements and suggest specific improvements to tailor your resume, including missing keywords, skills, and formatting recommendations.'
    },
    {
      question: 'How do I change my active resume?',
      answer: 'Go to Resume Versions from the sidebar, select the resume you want to set as active, and click "Set as Active". This resume will be used for all analysis and job matching.'
    },
    {
      question: 'How does job matching work?',
      answer: 'Our AI analyzes your resume and matches it against job postings based on skills, experience, keywords, and requirements. Each job shows a match percentage indicating how well your profile fits.'
    },
    {
      question: 'How do I use the AI Interviewer?',
      answer: 'Navigate to AI Interviewer, select your target role and difficulty level, then start the interview. The AI will ask relevant questions and provide feedback on your responses.'
    },
    {
      question: 'Can I compare different versions of my resume?',
      answer: 'Yes! Use the Resume Comparison feature to compare multiple resume versions side-by-side, seeing differences in ATS scores, skills, and other metrics.'
    },
    {
      question: 'What is the Career Roadmap?',
      answer: 'The Career Roadmap is a personalized development plan generated by AI based on your current skills and career goals. It shows recommended skills to learn, projects to build, and certifications to pursue.'
    },
    {
      question: 'How accurate is the AI Career Assistant?',
      answer: 'Our AI Career Assistant uses advanced language models trained on career development data. While highly accurate, recommendations should be used as guidance alongside professional career advice.'
    }
  ];

  const toggleFaq = (index) => {
    setExpandedFaq(expandedFaq === index ? null : index);
  };

  const filteredFaqs = searchQuery
    ? faqs.filter(faq => 
        faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        faq.answer.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : faqs;

  return (
    <AppLayout pageTitle="Help & Support">
      <div className="help-page">
        <div className="help-header">
          <h1>How can we help?</h1>
          <div className="help-search">
            <Input
              icon={<SearchIcon size={20} />}
              placeholder="Search help articles..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        </div>

        {/* Popular Topics */}
        <div className="help-section">
          <h2>Popular Topics</h2>
          <div className="help-topics">
            {popularTopics.map((topic, index) => (
              <Card key={index} className="help-topic" onClick={() => window.location.href = topic.link}>
                <div className="help-topic__icon">{topic.icon}</div>
                <h3>{topic.title}</h3>
              </Card>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div className="help-section">
          <h2>Frequently Asked Questions</h2>
          <div className="help-faq">
            {filteredFaqs.length === 0 ? (
              <Card className="help-empty">
                <p>No results found for "{searchQuery}"</p>
              </Card>
            ) : (
              filteredFaqs.map((faq, index) => (
                <Card key={index} className="help-faq-item">
                  <button
                    className="help-faq-question"
                    onClick={() => toggleFaq(index)}
                  >
                    <span>{faq.question}</span>
                    <ChevronDownIcon
                      size={20}
                      className={`help-faq-icon ${expandedFaq === index ? 'help-faq-icon--expanded' : ''}`}
                    />
                  </button>
                  {expandedFaq === index && (
                    <div className="help-faq-answer">
                      <p>{faq.answer}</p>
                    </div>
                  )}
                </Card>
              ))
            )}
          </div>
        </div>

        {/* Contact Support */}
        <Card className="help-contact">
          <h2>Still need help?</h2>
          <p>Our support team is here to assist you with any questions or issues.</p>
          <Button variant="primary">Contact Support</Button>
        </Card>
      </div>
    </AppLayout>
  );
};

export default Help;
